name: Cucumber Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      SEP_USERNAME: ${{ secrets.SEP_USERNAME }}
      SEP_PASSWORD: ${{ secrets.SEP_PASSWORD }}
      CARD_NUMBER: ${{ secrets.CARD_NUMBER }}
      EXPIRATION_DATE: ${{ secrets.EXPIRATION_DATE }}
      CVC: ${{ secrets.CVC }}
      ZIP_CODE: ${{ secrets.ZIP_CODE }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Cucumber tests
      run: npx cucumber-js
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: cucumber-report
        path: reports/
        retention-days: 30
